pipeline {
  agent any
  tools {
    maven 'maven-3.9.11' // doit correspondre au nom dans Manage Jenkins → Global Tool Configuration
    jdk   'jdk-21'       // idem pour le JDK
  }

  stages {
    stage('Build') {
      steps {
        // build en batch mode, tests sautés pour un build rapide
        sh 'mvn -B -DskipTests=true clean package'
      }
    }
  }

  post {
    success { echo 'Build succeeded' }
    failure { echo 'Build failed' }
  }
}
