pipeline {
  agent any
  tools {
    maven 'maven 3.9' 
    jdk   'jdk17'       // idem pour le JDK
  }

  stages {
    stage('Build') {
      steps {

        sh 'mvn -B -DskipTests=true clean package'
      }
    }
  }

  post {
    success { echo 'Build succeeded' }
    failure { echo 'Build failed' }
  }
}
